In [2]:
## importing libraries 
import pandas as pd 
from datasets import load_dataset
import matplotlib.pyplot as plt 

## loading data 
dataset= load_dataset('lukebarousse/data_jobs')
df= dataset['train'].to_pandas()

## data cleaning 
df['job_posted_date']=pd.to_datetime(df['job_posted_date'])

c:\Users\mahar\anaconda3\envs\python_youtube\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
## calculate project salary next year 
df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [4]:
def projected_salary(salary):
    return salary*1.03

df_salary= df[pd.notna(df['salary_year_avg'])].copy()
df_salary['salary_year_inflated']=df_salary['salary_year_avg'].apply(projected_salary)
df_salary[['salary_year_avg','salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [5]:
## without function project the inflated salry

df_salary['salary_year_inflated']=df_salary['salary_year_avg'].apply(lambda salary : salary *1.03)
df_salary[['salary_year_inflated','salary_year_avg']]

        salary_year_inflated  salary_year_avg
28                 112785.00         109500.0
77                 144200.00         140000.0
92                 123600.00         120000.0
100                235068.66         228222.0
109                 91670.00          89000.0
...                      ...              ...
785624             143392.48         139216.0
785641             154500.00         150000.0
785648             228531.25         221875.0
785682             162225.00         157500.0
785692             162225.00         157500.0

[22003 rows x 2 columns]

In [6]:
## string to list 
import ast 
type(ast.literal_eval(df['job_skills'][1]))

list

In [7]:
## doing it with lambda functiuon
df['job_skills']=df['job_skills'].apply(lambda clean : ast.literal_eval(clean) if pd.notna(clean) else clean)

In [8]:
## doing it without function 
def clean_list(skill_list):
    if pd.notna(skill_list):
     return ast.literal_eval(skill_list)

df['job_skills']= df['job_skills'].apply(clean_list)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [9]:
## checking the type of job skill
type(df['job_skills'][3])

list

In [ ]:
## apply function to row 
## calculate projected salary next year 
 ## senior roles 5% 
## other roles assume 3%

In [11]:
df_pro_sal= df[pd.notna(df['salary_year_avg'])].copy()
df_pro_sal

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"[gdpr, excel]","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"[mongodb, mongodb, python, r, sql, mysql, mari...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"[sql, python]","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"[sql, r, python, express]","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"[python, r, alteryx, tableau]","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"[go, python, r, sql, oracle, windows, alteryx,...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,NaN,"Engage Partners, Inc.",None,None
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"[python, azure, snowflake, spark]","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"[python, hadoop, spark, airflow, kubernetes]","{'libraries': ['hadoop', 'spark', 'airflow'], ..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"[python, matlab, r]","{'programming': ['python', 'matlab', 'r']}"

In [16]:
def pro_sal (row):
    if "Senior" in row['job_title_short']:
        return 1.05* row['salary_year_avg']
    else:
        return 1.03 * row['salary_year_avg']

In [18]:
df_pro_sal['projected_salary']= df_pro_sal.apply(pro_sal,axis=1)
df_pro_sal[['projected_salary','salary_year_avg']]

        projected_salary  salary_year_avg
28             112785.00         109500.0
77             144200.00         140000.0
92             123600.00         120000.0
100            235068.66         228222.0
109             91670.00          89000.0
...                  ...              ...
785624         143392.48         139216.0
785641         154500.00         150000.0
785648         228531.25         221875.0
785682         162225.00         157500.0
785692         162225.00         157500.0

[22003 rows x 2 columns]